### PR TITLE
Franklin us11

### PR DESCRIPTION
**Pull request by FranklinShack**
Added functionality to the notebuttons to add the notes to the answer boxes.  Changes made in game.js (adding IDs to answer boxes), notebutton (adding setNote), and a new file, SetNote.js

### CODE REVIEW

**Comment by FranklinShack** [comment]
Added the undo button as well.  Changes in game.js to add the button div, plus a new file, UndoSelection.js to handle the undo.

**Comment by coriwisniewski** [comment]
do we have unit tests for this?

**Comment by FranklinShack** [comment]
> do we have unit tests for this?

Will be making some after class.

**Comment by coriwisniewski** [comment]
everything works as expected here and looks really good, but we should probably move the onClick to the larger surrounding div (as opposed to tiny inside button) though in case the user wants to hear the sound and not select it - currently those buttons overlap so we can't do only one or the other.

**Comment by coriwisniewski** [comment]
buttons still overlap a little but it works for now. easily something I can make style changes to in my next user story or you can address next sprint as well.

**Pull request merged**
